[package]
name = "file-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["multipart", "json"] }
serde_json = "1.0.128"
axum = { version = "0.7.4", features = ["multipart"] }
shuttle-axum = "0.48.0"
shuttle-runtime = "0.48.0"
tokio = "1.28.2"
